server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.128:8848
        username: nacos
        password: nacos
        namespace: d022c08c-d058-4c47-86a0-0579574fb9b5
        group: chronic-disease-group
    gateway:
      routes:
        - id: user-service #微服务名称
          uri: lb://health-user-service #路由目标地址 lb代表负载均衡
          predicates: #路由判定规则
            - Path=/user/**,/dict/**,/archive/**,/doctor/**
        - id: health-record-service
          uri: lb://health-record-service
          predicates:
            - Path=/index/**,/medicine/**,/recheck/**,/consultation/**,/consultation-ws/**
        - id: health-remind-service
          uri: lb://health-remind-service
          predicates:
            - Path=/remind/**
        - id: health-article-service
          uri: lb://health-article-service
          predicates:
            - Path=/article/**
