spring:
  application:
    name: user-service
  config:
    import: nacos:user-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.128:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.248.128:8848
        username: nacos
        password: nacos
        namespace: public
        file-extension: yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.248.128:3306/db_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 20050603fsh..